### ISSUE TITLE
Add ability to override settings on application.

### ISSUE THREAD

**Issue by trackleft** [az-digital/pantheon-imagemagick-configuration#1]
## Motivation
I'd like to make my recipe slightly more flexible.

### Is your feature request related to a problem? Please describe.
The problem is that the recipe is not one size fits all.

## Proposed Resolution
Allow inputs for the two config options
- quality
- prepend

### Describe the solution you'd like
```
input:
  quality:
    data_type: integer
    description: 'Define the image quality for image manipulations'
    constraints:
      NotBlank: []
      Range: 
        min: 0
        max: 100
    prompt:
      method: ask
      arguments:
        question: 'Define the image quality for image manipulations. Ranges from 0 to 100. Higher values mean better image quality but larger files.'
    default:
      source: config
      config: ['imagemagick.settings', 'quality']
      value: 92
  prepend:
    data_type: string
    description: 'The imagemagick prepend command. '
    prompt:
      method: ask
      arguments:
        question: 'Add any prepend commands.'
    default:
      source: config
      config: ['imagemagick.settings', 'prepend']
      value: '-limit memory 64MiB'
config:
  actions:
    system.image:
      simple_config_update:
        toolkit: imagemagick
    imagemagick.settings:
      simple_config_update:
        quality: ${quality}
        prepend: ${prepend}
```
## Additional context
The readme should also be updated to explain how to add optional inputs.
